### ISSUE TITLE
[FEATURE REQUEST] Add position animation blending

### ISSUE THREAD

**Issue by KLONOA9X6** [GrandpaScout/GSAnimBlend#1]
Original animation (Using Yes Steve Model (GeckoLib core)):

https://github.com/GrandpaScout/GSAnimBlend/assets/95112579/3e0d1aa0-e79e-43ad-97ed-34324aff8def

Using Figura:
```
animations.main["sprint"]:blendTime(2.5)
```

https://github.com/GrandpaScout/GSAnimBlend/assets/95112579/67bc74ad-c57f-47e6-9a2e-8e77139427ae

**Comment by GrandpaScout** [comment]
Animation blending accounts for everything an animation can do already. It uses the built-in `:setBlend()` method created by Figura to handle blending in and out. This seems more like an issue with the animation itself.
